# Generated by Django 5.0.2 on 2024-02-28 15:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_dailyorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyorder',
            name='comment',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Izoh'),
        ),
        migrations.AddField(
            model_name='dailyorder',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.customer', verbose_name='Mijoz: '),
        ),
        migrations.AddField(
            model_name='dailyorder',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Yetkazilish sanasi: '),
        ),
        migrations.AddField(
            model_name='dailyorder',
            name='date_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Buyurtma yetkazilish vaqti'),
        ),
        migrations.AddField(
            model_name='dailyorder',
            name='order_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Buyurtma qilingan vaqti: '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailyorder',
            name='phone',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='dailyorder',
            name='phone1',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='dailyorder',
            name='quantity',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='buyurtma qilingan mahsulot soni: '),
        ),
    ]
