# Generated by Django 5.0.2 on 2024-02-28 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_dailyorder_comment_dailyorder_customer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorycustomer',
            options={'verbose_name_plural': 'Mijoz kategoriyalari'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name_plural': 'Mijozlar'},
        ),
        migrations.AlterModelOptions(
            name='dailyorder',
            options={'verbose_name_plural': 'Kunlik buyurtmalar'},
        ),
        migrations.AlterModelOptions(
            name='deliverydriver',
            options={'verbose_name_plural': 'Haydovchilar'},
        ),
        migrations.AlterModelOptions(
            name='localarea',
            options={'verbose_name_plural': 'Hudud'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': 'Buyurtmalar'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Mahsulotlar'},
        ),
    ]
