# Generated by Django 5.0.2 on 2024-02-29 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_categorycustomer_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderByDailyOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_address', models.CharField(max_length=255, verbose_name='Buyurtma manzili: ')),
                ('daily_order_quantity', models.IntegerField(verbose_name='Buyurtma qilingan mahsulot soni: ')),
                ('customer_phone', models.CharField(max_length=13)),
                ('customer_phone1', models.CharField(max_length=13)),
                ('received_quantity', models.IntegerField(default=0, verbose_name='Mijoz olgan mahsulot')),
                ('ordered_product_box', models.IntegerField(default=0, verbose_name='Olingan mahsulotning qutisi soni')),
                ('returned_product_box', models.IntegerField(blank=True, default=0, null=True, verbose_name='Qaytarilgan mahsulot qutisi soni')),
                ('debt_product_box', models.IntegerField(blank=True, default=0, null=True, verbose_name='Qarzdorlik: qutilardan')),
                ('total_amount', models.IntegerField(blank=True, default=0, null=True, verbose_name='Jami buyurtma summasi')),
                ('paid_amount', models.IntegerField(blank=True, default=0, null=True, verbose_name="Amalga oshirilgan to'lov")),
                ('debt_customer', models.IntegerField(default=0, verbose_name='Qarzdorlik')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('daily_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.dailyorder', verbose_name='Kunlik buyurtmalar: ')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.order', verbose_name='Yuborilayotgan yuk: ')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
