# Generated by Django 5.0.2 on 2024-03-01 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_orderbydailyorder_product_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderbydailyorder',
            options={'verbose_name_plural': 'Tayyor buyurtmalar'},
        ),
        migrations.AlterField(
            model_name='orderbydailyorder',
            name='customer_address',
            field=models.CharField(default='Manzil topilmadi', max_length=255, verbose_name='Buyurtma manzili: '),
        ),
        migrations.AlterField(
            model_name='orderbydailyorder',
            name='daily_order_quantity',
            field=models.IntegerField(default=0, verbose_name='Buyurtma qilingan mahsulot soni: '),
        ),
    ]
