# Generated by Django 5.0.2 on 2024-03-01 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_orderbydailyorder_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderbydailyorder',
            name='customer_phone1',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
