# Generated by Django 5.0.2 on 2024-03-02 07:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_orderbydailyorder_customer_phone1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyorder',
            name='date_time',
        ),
        migrations.AlterField(
            model_name='dailyorder',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Yetkazilish sanasi: '),
        ),
        migrations.CreateModel(
            name='Blacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blacklist', to='home.customer')),
            ],
        ),
    ]
