# Generated by Django 5.0.2 on 2024-03-02 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_blacklist_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklist',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='blacklist', to='home.customer'),
            preserve_default=False,
        ),
    ]
