# Generated by Django 5.0.2 on 2024-03-02 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_rename_customer_blacklist_customer_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blacklist',
            name='customer_deleted',
        ),
        migrations.AddField(
            model_name='blacklist',
            name='customer',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='blacklist', to='home.customer'),
            preserve_default=False,
        ),
    ]
