# Generated by Django 5.0.2 on 2024-03-02 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_dailyorder_customer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blacklist',
            options={'verbose_name_plural': "Qora ro'yxat"},
        ),
        migrations.AlterField(
            model_name='blacklist',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.customer', verbose_name='Bloklangan Mijoz'),
        ),
    ]
