# Generated by Django 5.0.2 on 2024-03-02 11:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_blacklist_options_alter_blacklist_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blacklist',
            name='customer',
        ),
        migrations.AddField(
            model_name='blacklist',
            name='address',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blacklist',
            name='name',
            field=models.CharField(default=0, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blacklist',
            name='phone',
            field=models.CharField(default=django.utils.timezone.now, max_length=13, unique=True),
            preserve_default=False,
        ),
    ]
