# Generated by Django 5.0.2 on 2024-03-02 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_oldcustomer_delete_blacklist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oldcustomer',
            options={'verbose_name_plural': "Qora Ro'yxat"},
        ),
    ]
