# Generated by Django 5.0.2 on 2024-03-03 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_oldcustomer_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyorder',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.customer', verbose_name='Mijoz: '),
            preserve_default=False,
        ),
    ]
