# Generated by Django 5.0.2 on 2024-03-03 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_alter_dailyorder_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyorder',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='buyurtma qilingan mahsulot soni: '),
        ),
    ]
