# Generated by Django 5.0.2 on 2024-03-03 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_alter_dailyorder_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyorder',
            name='quantity',
            field=models.IntegerField(verbose_name='buyurtma qilingan mahsulot soni: '),
        ),
    ]
