# Generated by Django 5.0.2 on 2024-03-03 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_alter_dailyorder_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyorder',
            name='date',
            field=models.DateTimeField(verbose_name='Yetkazilish sanasi: '),
        ),
    ]
