# Generated by Django 5.0.2 on 2024-03-03 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_alter_orderbydailyorder_customer_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderbydailyorder',
            name='customer_area',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Mahalliy hudud'),
        ),
    ]
