# Generated by Django 5.0.2 on 2024-03-14 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_alter_orderbydailyorder_customer_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderbydailyorder',
            name='customer_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Mijoz'),
        ),
    ]
